version: '3.8'

services:
  livox-ros2:
    build: .
    container_name: livox_ros2_driver
    network_mode: "host"
    volumes:
      - ./config:/ros2_ws/src/livox_ros2_driver/livox_ros2_driver/config
    tty: true
    stdin_open: true
