version: '3'

services:
  # MQTT to SQLite consumer
  mqtt_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt_livox_consumer
    network_mode: "host"  # Use host networking like in your working example
    environment:
      - BROKER_ADDRESS=192.168.50.191  # Your Raspberry Pi IP
      - BROKER_PORT=1883
      - TOPIC=livox/#  # Subscribe to all livox topics
      - DATA_DIR=/data
      - DB_FILENAME=livox_data.db
    volumes:
      - ./data:/data  # Mount a directory for persistent storage
    restart: unless-stopped