version: '3.8'

services:
  lidar_listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lidar_listener
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://192.168.50.191:11311  # IP of your Raspberry Pi
      - ROS_HOSTNAME=192.168.50.49                 # IP of your Mac
      - ROS_IP=192.168.50.49
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
