services:
  livox_ros1:
    build: .
    image: livox_ros1:latest
    container_name: livox_ros_driver
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - ./MID360_config.json:/home/livox/catkin_ws/src/livox_ros_driver2/config/MID360_config.json
    environment:
      - ROS_MASTER_URI=http://192.168.50.191:11311
      - ROS_HOSTNAME=192.168.50.191
      - MQTT_BROKER=192.168.50.49 # CHANGE THIS to your Mac Mini's IP address
      - MQTT_PORT=1883
    ports:
      - "11311:11311"
    restart: unless-stopped

  # The mqtt-broker service has been removed since it will run on the Mac Mini
