services:
  livox_ros1:
    build: .
    image: livox_ros1:latest
    container_name: livox_ros_driver
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - ./MID360_config.json:/home/livox/catkin_ws/src/livox_ros_driver2/config/MID360_config.json
    environment:
      # - ROS_MASTER_URI=http://192.168.50.191:11311
      # - ROS_HOSTNAME=192.168.50.191
      - MQTT_BROKER=192.168.50.49  # Change this to your Mac's IP if needed
      - MQTT_PORT=1883
    ports:
      - "11311:11311"
      - "1883:1883"  # MQTT port
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    # network_mode: "host"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"  # WebSocket port for web clients
    restart: unless-stopped