services:
  livox_ros1:
    build: .
    image: livox_ros1:latest
    container_name: livox_ros_driver
    network_mode: "host"
    tty: true
    stdin_open: true
    # Add privileged mode for picamera access
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - ./MID360_config.json:/home/livox/catkin_ws/src/livox_ros_driver2/config/MID360_config.json
      # Mount the entire /dev directory for camera access
      - /dev:/dev
      # Mount the camera interface
      - /opt/vc:/opt/vc
      - /run/udev:/run/udev:ro
    environment:
      - ROS_MASTER_URI=http://192.168.50.191:11311
      - ROS_HOSTNAME=192.168.50.191
      - MQTT_BROKER=192.168.50.49 # Your Mac Mini's IP address
      - MQTT_PORT=1883
      - PYTHONPATH=/opt/vc/lib:$PYTHONPATH
      - LD_LIBRARY_PATH=/opt/vc/lib:$LD_LIBRARY_PATH
    ports:
      - "11311:11311"
    restart: unless-stopped
